export const portfolioSeo = [
    {
        id : 'Living-Room',
        description : 'Welcome to our Living Room Design Showcase, where we invite you to explore a collection of meticulously crafted living spaces that exemplify our dedication to creating inviting, stylish, and functional interiors. Step into a world of comfort and elegance as you immerse yourself in the art of living room design.',
        keywords : ['Living room design, Living room showcase, Stylish living rooms, Furniture selection, Space optimization, Accessorizing living rooms, Comfort and elegance']
    },
    {
        id : 'Bedroom',
        description : 'Welcome to our Bedroom Portfolio, where we invite you to discover a collection of enchanting and serene retreats that showcase our expertise in creating dreamy and personalized bedroom spaces. Immerse yourself in a world of comfort, style, and tranquility as you explore our portfolio of exceptional bedroom designs. Each bedroom project in our portfolio reflects our commitment to crafting intimate sanctuaries that promote relaxation and rejuvenation. From luxurious master suites to cozy guest bedrooms, our designs embrace a harmonious balance between functionality and aesthetics, catering to the unique preferences and lifestyles of our clients.',
        keywords : ['Bedroom design, Bedroom portfolio, Serene retreats, Personalized bedrooms, Comfort and style, Master suites, Guest bedrooms, Luxury bedding']
    }, 
    {
        id : 'Kids-Room',
        description: "Welcome to our Kids' Room Portfolio, where imagination comes to life and every corner tells a story of wonder and joy. Discover a collection of enchanting and whimsical designs that are crafted with love and care to create magical spaces for children to dream, play, and grow.",
        keywords: [
          "Kids' room design",
          "Kids' room portfolio",
          "Imaginative spaces",
          "Whimsical designs",
          "Playful environments",
          "Vibrant colors",
          "Cozy bedrooms",
          "Interactive features",
          "Age-appropriate furniture",
          "Safety and functionality",
          "Playrooms",
          "Wall murals",
          "Creative storage solutions",
          "Reading nooks",
          "Study areas",
          "Adventure-themed rooms",
          "Nature-inspired designs",
          "Princess-themed rooms",
          "Magical realms",
          "Sparking imagination",
          "Creative play",
          "Customizable spaces",
          "Growing with your child",
          "Lasting memories",
          "Sense of belonging"
        ]
    },
    {
        id : 'Bathroom',
        description: "Welcome to our Bathroom Portfolio, where luxury, functionality, and serenity converge to create exceptional bathing spaces. Explore our collection of meticulously designed bathrooms that combine innovative concepts, exquisite materials, and thoughtful details to transform everyday routines into indulgent experiences.",
        keywords: [
          "Bathroom design",
          "Bathroom portfolio",
          "Luxury bathrooms",
          "Functional spaces",
          "Serene retreats",
          "Contemporary bathrooms",
          "Minimalist designs",
          "Classic bathrooms",
          "Opulent bathrooms",
          "Tranquility and relaxation",
          "Intelligent storage solutions",
          "Premium materials",
          "Tiles and countertops",
          "High-quality fittings",
          "Spa-like sanctuaries",
          "Modern powder rooms",
          "Soothing color palettes",
          "Invigorating lighting schemes",
          "Rejuvenation and self-care",
          "Family-friendly bathrooms",
          "Statement-making guest bathrooms",
          "Elegance and functionality",
          "Transformative design",
          "Haven of relaxation",
          "Luxury and indulgence"
        ]
    },
    {
        id : 'Balcony-Terrace',
        description: "Welcome to our Balcony/Terrace Portfolio, where outdoor living meets elevated design. Step into a world of inspiring outdoor spaces that blur the boundaries between nature and artistry. Explore our collection of meticulously curated balcony and terrace designs that transform ordinary outdoor areas into breathtaking extensions of your living space.",
        keywords: [
          "Balcony design",
          "Terrace design",
          "Outdoor living",
          "Elevated spaces",
          "Nature-inspired designs",
          "Cozy balconies",
          "Spacious terraces",
          "Personal style",
          "Relaxation and entertainment",
          "Connection with nature",
          "Space optimization",
          "Comfortable seating areas",
          "Greenery and planters",
          "Furniture arrangements",
          "Stylish lighting solutions",
          "Captivating decor",
          "Urban oasis",
          "Social gathering spot",
          "Serene retreat",
          "Panoramic views",
          "Thoughtful layouts",
          "Sustainable materials",
          "Creative features",
          "Harmonious outdoor experience",
          "Memorable moments"
        ]
    },
    {
        id : 'Office-Interior',
        description: "Welcome to our Office Interior Portfolio, where functionality, productivity, and aesthetics converge to create inspiring workspaces. Explore a collection of meticulously crafted office designs that blend comfort, professionalism, and innovation to elevate the work environment and enhance business success...",
        keywords: [
          "Office interior design",
          "Office interior portfolio",
          "Functionality and aesthetics",
          "Productive workspaces",
          "Professional environments",
          "Corporate offices",
          "Creative studios",
          "Co-working spaces",
          "Collaboration and productivity",
          "Employee well-being",
          "Ergonomic layouts",
          "Intelligent space planning",
          "Strategic lighting",
          "Efficient workflows",
          "Innovative technology",
          "High-quality materials",
          "Contemporary design elements",
          "Brand identity",
          "Modern aesthetics",
          "Minimalist offices",
          "Sophisticated styles",
          "Functional workstations",
          "Collaborative areas",
          "Ergonomic furniture",
          "Captivating decor"
        ]
    }
      
        
]