import Head from 'next/head'
import Header from '@/components/Header/Header'
import OurServices from '@/components/Homepage/OurServices'
import WhyChooseUs from '@/components/Homepage/WhyChooseUs'
import Footer from '@/components/Footer'
import PageWrapper from '@/components/PageWrapper/PageWrapper'
import IntroVideo from '@/components/Homepage/IntroVideo'
import AboutUs from '@/components/Homepage/Aboutus'
import Testimonials from '@/components/Homepage/Testimonials/Testimonials'
import Specialization from '@/components/Homepage/Specialization/Specialization'
import Image from 'next/image'
import whatsppImage from '@/public/Images/whatsapp_icon.png'

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Space Styler | Transforming Spaces In Style</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{position : 'relative'}}>
        <Header active="home"/>
        <IntroVideo />
        <PageWrapper>
        <AboutUs />
        <OurServices />
        </PageWrapper>
        <WhyChooseUs />
        <Specialization />
        <Testimonials />
        <div style={{position : 'fixed', top: '85vh', zIndex : 888, left : '50px'}}>
          <a href="https://api.whatsapp.com/send/?phone=7778885464&text=Hi%2C+I+need+an+interior+designer.&type=phone_number&app_absent=0" target="_blank">
            <Image
              src={whatsppImage}
              height={50}
              width={50}          
              />
          </a>
        </div>
      </main>
      <Footer />
    </>
  )
}
