import Head from 'next/head'
import Header from '@/components/Header/Header'
import OurServices from '@/components/Homepage/OurServices'
import WhyChooseUs from '@/components/Homepage/WhyChooseUs'
import Footer from '@/components/Footer'
import PageWrapper from '@/components/PageWrapper/PageWrapper'
import IntroVideo from '@/components/Homepage/IntroVideo'
import AboutUs from '@/components/Homepage/Aboutus'
import Testimonials from '@/components/Homepage/Testimonials/Testimonials'
import Specialization from '@/components/Homepage/Specialization/Specialization'

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Space Styler | Transforming Spaces In Style</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header active="home"/>
        <IntroVideo />
        <PageWrapper>
        <AboutUs />
        <OurServices />
        </PageWrapper>
        <WhyChooseUs />
        <Specialization />
        <Testimonials />
      </main>
      <Footer />
    </>
  )
}
