import Head from 'next/head'
import Header from '@/components/Header/Header'
import Banner from '@/components/Banner/Banner'
import OurServices from '@/components/Homepage/OurServices'
import WhyChooseUs from '@/components/Homepage/WhyChooseUs'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Space Styler | Transforming Spaces In Style</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header active="home"/>
        <Banner h={500}/>
        <OurServices />
        <WhyChooseUs />
      </main>
      <Footer />
    </>
  )
}
